/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/8.1.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    /* module 3.1 - actors - akka*/
    implementation(platform("com.typesafe.akka:akka-bom_2.13:2.8.2"))
    implementation("com.typesafe.akka:akka-actor-typed_2.13")
    testImplementation("com.typesafe.akka:akka-actor-testkit-typed_2.13")

    /* logging framework SLF4J */
    implementation("org.slf4j:slf4j-api:2.0.7")
    // testImplementation 'org.slf4j:slf4j-reload4j:2.0.7'
    implementation("org.slf4j:slf4j-simple:2.0.7")

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(20))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("pcd.assignment3.App")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
